BitByte-TPC/gymkhana

.github/workflows/ui-continuous_integeration.yml
- build
- test
- lint check
closes #6
=> ci(ui): add github action for ui

.github/workflows/api-tests.yml, api/api/settings.py, api/pytest.ini, api/requirements.txt
=> chore(api): add pytest as the test runner

.github/workflows/api-tests.yml, api/requirements.txt
=> ci: Code Coverage Report

.github/workflows/api-tests.yml, api/setup.cfg
- style(api): add flake8 config file
=> style(api): add flake8 config

CONTRIBUTING.md
=> docs(global): update CONTRIBUTING.md for backend

CONTRIBUTING.md, README.md, api/README.md, ui/README.md
- Move ui & api setup to their respective README
- Add more details about tech stack
- format code
closes #28
=> docs(global): update README.md and CONTRIBUTING.md

api/Dockerfile, api/README.md
=> chore(api): dockerize api

README.md
Fixes API readme link and UI setup links in global readme
Fixes #45
=> docs(global): update README.md

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
Adding issue templates for `bug reports` and `feature requests`
Signed-off-by: yusufadell <youssef.31057404@ics.tanta.edu.eg>
=> chore(global): add issue templates 

api/.env.template
=> fix(api): add correct cors origin

ui/package.json
=> fix(ui): failing tests on importing css

ui/package-lock.json, ui/package.json, ui/src/api/googleOauth.ts, ui/src/global.d.ts, ui/src/testSetup.ts, ui/src/tests/pages/Login.test.tsx
=> test(ui): add tests for Login component

api/api/accounts/fixtures/user_data.json
Fixes part of : #75 
Added fixture for superuser with following data - 
1. email - admin@iiitdmj.ac.in, password - Admin@gymkhana
2. email - adminstaff@iiitdmj.ac.in, password - Admin@gymkhana
=> Add fixture for superuser

api/Dockerfile, api/README.md, api/scripts/makemigrations.sh
=> feat(api): add bash script to make migrations

api/api/auth/backend.py, api/api/auth/tests.py, api/api/auth/views.py, api/api/settings/settings.py, api/api/views.py
=> feat(api): add auth middleware

api/api/settings/settings.py
=> fix[API]: make BASE_DIR in settings.py to refer right directory.

api/api/events/apps.py, api/api/events/models.py
=> feat(api): add event model

ui/.eslintrc.js, ui/package-lock.json, ui/package.json, ui/src/Routes.tsx, ui/src/components/Button/index.tsx, ui/src/components/Button/styles.module.css, ui/src/components/FormComponents/Input.tsx, ui/src/components/FormComponents/Textarea.tsx, ui/src/components/FormComponents/styles.module.css, ui/src/components/ProfileCard/index.tsx, ui/src/components/ProfileCard/styles.module.css, ui/src/index.css, ui/src/pages/Profile/index.tsx, ui/src/pages/Profile/styles.module.css
I have added a basic profile page. We can change the fields and design later.
=> feat: add basic profile page

api/Dockerfile.dev, api/scripts/populate_db.sh, docker-compose.yml, ui/Dockerfile.dev
=> build(app): Dockerize full app for development

ui/package-lock.json, ui/package.json, ui/src/components/Layout/Layout.tsx
Added `classnames` npm package for better conditional classes readability.
closes #151
=> refactor(ui): introduce classnames for conditional css classes

api/api/auth/serializers.py, api/api/auth/tests.py
- Changed TokenUserSerializer fields to include user id.
=> fix(api): add user.id to auth response

ui/package-lock.json, ui/package.json, ui/src/ProtectedRoute.test.tsx, ui/src/components/ClubsCarousel/index.tsx, ui/src/components/ClubsCarousel/styles.module.scss, ui/src/components/EventsCarousel/EventsCarousel.test.ts, ui/src/components/EventsCarousel/index.tsx, ui/src/components/EventsCarousel/styles.module.scss, ui/src/components/HeadingDropdown/index.tsx, ui/src/components/Layout/styles.module.scss, ui/src/globals/constants.ts, ui/src/index.scss
=> feat(ui): add dropdown for clubs & events

ui/src/components/ClubsCarousel/index.tsx, ui/src/components/Layout/styles.module.scss
=> Sidebar fix

ui/src/components/Sidebar/Sidebar.tsx
[UI] Redirect user to profile's page on clicking settings in sidebar
=> Redirect user to profile page

ui/src/components/Sidebar/Sidebar.tsx, ui/src/components/Sidebar/styles.module.scss
Added feature where on clicking gymkhana logo redirects to home
=> feat(ui): on clicking logo redirect to home

ui/src/components/ClubsCarousel/index.tsx, ui/src/pages/Club/index.tsx
=> fix(ui): use slug instead of clubname

ui/src/components/EventsCarousel/EventsCarousel.test.ts, ui/src/components/EventsCarousel/index.tsx, ui/src/components/EventsCarousel/styles.module.scss
I made the necessary changes in test.ts aswell
=> feat(ui): fetched events data from api

ui/src/components/TopBar/index.tsx, ui/src/components/TopBar/styles.module.scss
=> feat(ui): on clicking profile icon redirect to profile
